### ISSUE TITLE
Is fair the comparison of CBMI with other methods?

### ISSUE THREAD

**Issue by nomadlx** [songmzhang/CBMI#1]
I noticed that your method introduced LM Loss, which has been verified by [previous papers](https://arxiv.org/abs/2105.11098) can improve the quality of translation. But does your baseline and other methods were also introduced LM loss? The improvement in this paper seems to be more due to the introduction of LM Loss, as in the paper mentioned above, the introduction of LM Loss resulted in a 0.75 improvement in the WMT EN-DE dataset(see Table 1), and your reported improvement was 0.91. Can you provide a baseline with LM Loss?

**Comment by songmzhang** [comment]
> I noticed that your method introduced LM Loss, which has been verified by [previous papers](https://arxiv.org/abs/2105.11098) can improve the quality of translation. But does your baseline and other methods were also introduced LM loss? The improvement in this paper seems to be more due to the introduction of LM Loss, as in the paper mentioned above, the introduction of LM Loss resulted in a 0.75 improvement in the WMT EN-DE dataset(see Table 1), and your reported improvement was 0.91. Can you provide a baseline with LM Loss?

Thanks for your attention. The difference of the LM loss between (Miao et al. 2021) and ours is that **they share the embeddings of Transformer with the LM while we do not**. In our method, the LM has no parameter-overlap with the original Transformer, and thus it has no effect on the NMT training except for the CBMI calculation. So we think it is fair to compare it with other methods.
We also tried to follow the setting in (Miao et al. 2021) to share the embedding in our early experiments, however, we failed to re-implement the improvement in their paper (similar results with no-share), so we just decouple the two models in the following experiments.
